In [1]:
import json
import pandas as pd

In [20]:
data = []

with open('短短匹配A类/train.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('短短匹配A类/valid.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))  
        
with open('短短匹配B类/train.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('短短匹配B类/valid.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
df1 = pd.DataFrame(data)
df1['type'] = 'ss'
df1['len1'] = df1['source'].apply(len)
df1['len2'] = df1['target'].apply(len)

print(df1.len1.describe(), df1.len2.describe())
df1

count    23013.000000
mean        57.412115
std         48.365259
min          3.000000
25%         23.000000
50%         30.000000
75%        105.000000
max        150.000000
Name: len1, dtype: float64 count    23013.000000
mean        57.671968
std         48.050133
min          3.000000
25%         23.000000
50%         30.000000
75%        105.000000
max        150.000000
Name: len2, dtype: float64

,source,target,labelA,labelB,type,len1,len2
0,谁能打破科比81分纪录？奥尼尔给出5个候选人，补充利拉德比尔！,NBA现役能入名人堂的球星很多，但是能被立铜像只有2人,0,NaN,ss,31,27
1,请扩散！明天，黄金埠这些地方会停电！,生活｜这几个地方注意啦！1月12日有部分线路停电检修,0,NaN,ss,18,26
2,居家健身增强免疫！（三）,原来是背影杀手#你愿意和我做朋友吗#户外健身,0,NaN,ss,12,22
3,太极拳罗师傅被洋人打伤，叶问霸气复仇？,非常完美：感动！女嘉宾告白赵杰被拒绝，尹康霸气上台挽留！,0,NaN,ss,19,30
4,恭喜哈登！篮网因祸得福，29+7超巨大概率复出，3换4交易方案出炉,三英缺席杜兰特，篮网迎战湖人NBA重头大戏！,1,NaN,ss,33,22
...,...,...,...,...,...,...,...
23008,好久不见《粤语歌曲就算我做错》,好久不见《王麟思密达(DJAlexx舞曲)》,NaN,0,ss,15,24
23009,本场火箭球员评分——伍德（9.5分）出场35分钟，18投10中，三分7中5，27分15板1助...,在主场分别是以18分和17分惨败湖人，这样的结果并不丢人，但让人无法接受的是火箭输球的方式，...,NaN,0,ss,92,146
23010,《赘婿》：苏檀儿为何不接受乌启豪？因为乌启豪根本不爱她,《赘婿》原著：宁毅娶了八个老婆，苏檀儿曾坦言后悔让宁毅入赘,NaN,0,ss,27,29
23011,春节档7部大片王者争霸,春节档7部大片王者争霸,NaN,1,ss,11,11
23012,说起春节联欢晚会，相信大家对这个节目并不陌生。他说她是一个著名的歌手，一个国家一级演员是一个...,备受关注的是，南充原创舞蹈《雪·暗香》亮相此次全球华人盛会，这个蕴含中国传统文化的舞蹈吸引了...,NaN,0,ss,148,144

In [21]:
data = []

with open('短长匹配A类/train.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('短长匹配A类/valid.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))  
        
with open('短长匹配B类/train.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('短长匹配B类/valid.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
df2 = pd.DataFrame(data)
df2['type'] = 'sl'
df2['len1'] = df2['source'].apply(len)
df2['len2'] = df2['target'].apply(len)

print(df2.len1.describe(), df2.len2.describe())
df2

count    23185.000000
mean       112.273668
std        272.634416
min          3.000000
25%         25.000000
50%         33.000000
75%        129.000000
max       9988.000000
Name: len1, dtype: float64 count     23185.000000
mean        968.848782
std        1553.134889
min           4.000000
25%         460.000000
50%         772.000000
75%        1160.000000
max      183608.000000
Name: len2, dtype: float64

,source,target,labelA,labelB,type,len1,len2
0,世界顶尖级的鞍马竞赛，动作很到位！,全文共962字，阅读大约需要2分20秒。 “ 我们坚定地认为，“身体和灵魂，总有一个要...,0,NaN,sl,19,951
1,鸬鹚与鱼，杭州翁剑敏/摄影 普通鸬鹚，大型水鸟。在中国南方较常见。通体黑色，头颈具紫绿色光...,【好消息！钱塘江新建大桥最快6月合龙】看浙里钱塘江新建大桥位于彭埠大桥（钱江二桥）下游侧，全...,0,NaN,sl,101,159
2,据大连市纪委监委消息：1月13日晚，网络传出大连市金普新区一女子进小区拒不配合志愿者登记并给...,据大连市纪委监委消息：1月13日晚，网络传出大连市金普新区一女子进小区拒不配合志愿者登记并给...,0,NaN,sl,62,829
3,诠释何为英雄本色，这就是巴蒂。 免责声明平台重在分享，除署名外其余内容均来自网络，我们对文...,近日，湖人球星勒布朗在社交媒体上晒出一组电影《空中大灌篮2：新传奇》的剧照，他也登上了《娱乐...,0,NaN,sl,102,551
4,大 红 包 爆笑喜剧电影《大红包》提档1月22日，正式拉响2021新年喜剧贺岁的首战号角...,大红包抢先看 开年必须哈哈哈 大 红 包 爆笑喜剧电影《大红包》1月22日上映，“特...,1,NaN,sl,150,564
...,...,...,...,...,...,...,...
23180,中国最年轻跳水女皇，跷二郎腿会见领导，24岁退役，今成气质女神 谈及中国跳水队，极易让人想到...,耳根可以掌控左脑妄念，传导右脑本能发挥极致，同时支配太极拳走架，直接开显灵觉智能。 传统太极...,NaN,0,sl,150,4099
23181,乔安女王气场全开，一招吓退总裁前女友，太霸气了,北京时间2月28日，英超联赛传来重磅消息，据英国媒体《镜报》报道，一旦德国最新向克洛普发出执...,NaN,0,sl,25,549
23182,四川双加时险胜上海弗雷戴特70+9+8亨特68分,CBA又见外援神仙打架！四川对阵上海，亨特和弗雷戴特上演对飙大战，第四节最后时刻弗雷戴特命中...,NaN,1,sl,24,874
23183,许多人都说，因为当年舅舅庄静庵不准表妹庄月明嫁给自己，李嘉诚跟舅舅庄静庵一度不和，后来在媒体...,《浪姐2》大家pick了谁？本来我是去看搞笑英英子的，没想到爱上了吉克隽逸和杨钰莹。 Mom...,NaN,0,sl,101,3943
23184,张艺谋和小31岁娇妻近照，曾在一起十年三个孩子未领证,陈婷晒老公儿子片场照，张艺谋变老小孩与儿子玩攥拳猜物，超温馨 1月30日晚，著名导演张艺谋妻...,NaN,0,sl,26,767

In [22]:
data = []

with open('长长匹配A类/train.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('长长匹配A类/valid.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))  
        
with open('长长匹配B类/train.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('长长匹配B类/valid.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
df3 = pd.DataFrame(data)
df3['type'] = 'll'
df3['len1'] = df3['source'].apply(len)
df3['len2'] = df3['target'].apply(len)

print(df3.len1.describe(), df3.len2.describe())
df3

count    23380.000000
mean      1063.049016
std       1151.303120
min        100.000000
25%        556.000000
50%        835.000000
75%       1242.000000
max      77827.000000
Name: len1, dtype: float64 count    23380.000000
mean      1053.077716
std       1046.752596
min        104.000000
25%        546.000000
50%        831.000000
75%       1230.000000
max      45327.000000
Name: len2, dtype: float64

,source,target,labelA,labelB,type,len1,len2
0,最近 你有没有约上好友一起去看电影？ 观影的感觉是不是很爽…… 不过 消防蜀黍在这里还得啰嗦...,最近 你有没有约上好友一起去看电影？ 观影的感觉是不是很爽…… 不过 消防蜀黍在这里还得啰嗦...,1,NaN,ll,818,835
1,"就算韩国娱乐圈中新来的艺人是一个接着一个，""首席御姐""的座位也没有任何人去争抢。 这个位置能...","作为""霸道总裁""的王耀庆，即使不想成为一个演员。 却也因为自己的""手滑""填错了志愿，从此踏上...",0,NaN,ll,1505,1455
2,1月13日， 在地铁3号线清江路站早高峰期间， 发生了这样惊险的一幕 事件回顾 7:40分...,千盼万盼 洛阳人离地铁越来越近 实拍！洛阳地铁1号线试运行...... （点击文字链接查看详...,1,NaN,ll,589,7703
3,新华社联合国1月7日电中国常驻联合国代表团发言人7日说，据媒体报道，美国国务卿蓬佩奥称美国常...,【美国常驻联合国代表克拉夫特访台计划取消，外交部回应】据路透社消息，美国国务院发言人12日宣...,1,NaN,ll,377,279
4,自贡市管治结合，狠抓春季森林防火。 一是严格火源管控。全面实行护林护草人员在线巡护，在国有林...,“世界之大，无奇不有”在我们生活的这个世界上，生活着许许多多可爱又聪明的小动物！它们以一种憨...,0,NaN,ll,377,582
...,...,...,...,...,...,...,...
23375,凯尔特人是苏超的霸主，不过随着格拉斯哥流浪者本赛季的强势回归，球队本赛季遭遇了前所未有的挑战...,019，利物浦vs曼特斯特联 利物浦上赛季遥遥领先的拿到了冠军，本以为利物浦是准备做百分...,NaN,0,ll,341,1517
23376,谁是中国影史最另类的导演？ 答案只有一个：姜文。 能够切中时代脉搏，真正做到商业与艺术的完...,最近，有眼尖的网友发现，在电视剧版《天官赐福》豆瓣页面，导演一栏竟然是姜文。 虽然这大概率...,NaN,1,ll,3635,2210
23377,“建设海南自由贸易港，打造我国面向太平洋、印度洋的重要开放门户，是国家重大战略。”近日，中国...,法国：禽类及其相关产品暂停输华 近日，法国官方通报该国家禽发生H5N8亚型高致病性禽流感疫情...,NaN,0,ll,1658,1806
23378,[辉瑞和Moderna现在承诺，到7月底前将在美国分别生产3亿剂疫苗，并在欧洲和其他地区生产...,国际在线报道（记者高俊雅）：南非总统拉马福萨2月28号宣布，随着该国每日新增病例的持续下降以...,NaN,0,ll,1658,759
23379,【作者：楠鱼说娱乐】 说起吴孟达，作为港片里的黄金配角，很多电影都有他的身影，当然了大家印象...,近日，各媒体都在关注和报道吴孟达病情状况，虽然本人或家人都没有回应，但好友田启文却时不时透露...,NaN,0,ll,783,907

In [23]:
df = pd.concat([df1,df2,df3])
df

,source,target,labelA,labelB,type,len1,len2
0,谁能打破科比81分纪录？奥尼尔给出5个候选人，补充利拉德比尔！,NBA现役能入名人堂的球星很多，但是能被立铜像只有2人,0,NaN,ss,31,27
1,请扩散！明天，黄金埠这些地方会停电！,生活｜这几个地方注意啦！1月12日有部分线路停电检修,0,NaN,ss,18,26
2,居家健身增强免疫！（三）,原来是背影杀手#你愿意和我做朋友吗#户外健身,0,NaN,ss,12,22
3,太极拳罗师傅被洋人打伤，叶问霸气复仇？,非常完美：感动！女嘉宾告白赵杰被拒绝，尹康霸气上台挽留！,0,NaN,ss,19,30
4,恭喜哈登！篮网因祸得福，29+7超巨大概率复出，3换4交易方案出炉,三英缺席杜兰特，篮网迎战湖人NBA重头大戏！,1,NaN,ss,33,22
...,...,...,...,...,...,...,...
23375,凯尔特人是苏超的霸主，不过随着格拉斯哥流浪者本赛季的强势回归，球队本赛季遭遇了前所未有的挑战...,019，利物浦vs曼特斯特联 利物浦上赛季遥遥领先的拿到了冠军，本以为利物浦是准备做百分...,NaN,0,ll,341,1517
23376,谁是中国影史最另类的导演？ 答案只有一个：姜文。 能够切中时代脉搏，真正做到商业与艺术的完...,最近，有眼尖的网友发现，在电视剧版《天官赐福》豆瓣页面，导演一栏竟然是姜文。 虽然这大概率...,NaN,1,ll,3635,2210
23377,“建设海南自由贸易港，打造我国面向太平洋、印度洋的重要开放门户，是国家重大战略。”近日，中国...,法国：禽类及其相关产品暂停输华 近日，法国官方通报该国家禽发生H5N8亚型高致病性禽流感疫情...,NaN,0,ll,1658,1806
23378,[辉瑞和Moderna现在承诺，到7月底前将在美国分别生产3亿剂疫苗，并在欧洲和其他地区生产...,国际在线报道（记者高俊雅）：南非总统拉马福萨2月28号宣布，随着该国每日新增病例的持续下降以...,NaN,0,ll,1658,759
23379,【作者：楠鱼说娱乐】 说起吴孟达，作为港片里的黄金配角，很多电影都有他的身影，当然了大家印象...,近日，各媒体都在关注和报道吴孟达病情状况，虽然本人或家人都没有回应，但好友田启文却时不时透露...,NaN,0,ll,783,907

In [24]:
df.labelA.value_counts(),df.labelB.value_counts()

(0    22107
 1    12687
 Name: labelA, dtype: int64,
 0    28757
 1     6027
 Name: labelB, dtype: int64)

In [25]:
df.to_csv('train.csv', index=False)

In [26]:
data = []

with open('短短匹配A类/test_with_id.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('短短匹配B类/test_with_id.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
df1 = pd.DataFrame(data)
df1['type'] = 'ss'
df1['len1'] = df1['source'].apply(len)
df1['len2'] = df1['target'].apply(len)

print(df1.len1.describe(), df1.len2.describe())
df1

count    9864.000000
mean       58.128548
std        48.752310
min         4.000000
25%        23.000000
50%        30.000000
75%       107.000000
max       150.000000
Name: len1, dtype: float64 count    9864.000000
mean       58.532543
std        48.486341
min         3.000000
25%        24.000000
50%        30.000000
75%       107.000000
max       150.000000
Name: len2, dtype: float64

,source,target,id,type,len1,len2
0,北京顺义2个地区调整为低风险地区,黑龙江省大庆市中风险地区清零全域调为低风险,ss0_a,ss,16,21
1,库里夺冠希望渺茫！荣誉或就此而止，退役后进不了历史前十,维金斯：勇士文化是不同的这可能是我生涯最开心的阶段,ss1_a,ss,27,25
2,过年了，过年了！,就地过年的你，许愿吗？,ss2_a,ss,8,14
3,你见过被噎死的蛇吗？这条蛇自作自受吞下庞然大物把自己给撑死了！,这种瓜有人从来没见过，这里却做全瓜宴,ss3_a,ss,31,20
4,如果你喜欢关注足球赛事、喜欢讨论赛事战术打法、了解豪门球队背后的历史渊源、喜爱投资足彩竞彩…...,大家好，我是小狼！前天利物浦客场3:1击败铁锤帮西汉姆联，红军打进的第二个进球太漂亮了，就像...,ss4_a,ss,148,150
...,...,...,...,...,...,...
9859,凡习练太极拳有一定时日的人，一般都会注意到王宗岳的《太极拳论》，其原因是王宗岳的《太极拳论》...,35 旋风脚 记住太极拳练习的10个不要！ 01 过分用意 意念过重容易出偏差。有人认为...,ss4925_b,ss,149,145
9860,调皮王妃：嫣然服毒自尽，尹昊为爱以身试药，实在太感人！,NPC队员投票表决，尤长靖不同意少数服从多数，小鬼：你要不出,ss4926_b,ss,29,32
9861,【英冠】赛事前瞻：伯恩茅斯vs米尔沃尔，伯恩茅斯利刃出鞘,红单燥起来意甲：桑普多利亚表现非常跳跃，乌迪内斯6战未尝胜绩士气低迷,ss4927_b,ss,28,34
9862,泛亚环保独立非执行董事辞世,"每经AI快讯，中教控股（00839,HK）宣布，广州大学松田学院已于近日获中国教育部批准自一...",ss4928_b,ss,13,138
9863,篮球解析：辽宁飞豹VS深圳领航者,东部和联盟倒数第二的猛龙队，怎么都想不到会打得如此糟糕，在结束的一段西部四连客之旅中，仅仅...,ss4929_b,ss,16,65

In [27]:
data = []

with open('短长匹配A类/test_with_id.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('短长匹配B类/test_with_id.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
df2 = pd.DataFrame(data)
df2['type'] = 'sl'
df2['len1'] = df2['source'].apply(len)
df2['len2'] = df2['target'].apply(len)

print(df2.len1.describe(), df2.len2.describe())
df2

count     9938.000000
mean       116.655061
std        437.392666
min          3.000000
25%         25.000000
50%         34.000000
75%        129.000000
max      35355.000000
Name: len1, dtype: float64 count     9938.000000
mean       955.169149
std        962.283897
min          6.000000
25%        455.000000
50%        766.000000
75%       1144.000000
max      24482.000000
Name: len2, dtype: float64

,source,target,id,type,len1,len2
0,瞿丰林介绍说，巡查人员发现，部分市民将共享电动车上的头盔剪下后占为己有，“虽然头盔被盗数量比...,据河北省吴桥县公安局微信公众号“吴桥公安”3月3日消息，吴桥公安3月3日发布《案情通报》： ...,sl0_a,sl,118,3101
1,首次试飞！安徽这一机场即将正式通航！,2021年1月13日，芜湖宣州机场迎来投运前的重要时刻——一架中国东方航空公司空客A320型...,sl1_a,sl,18,1225
2,十三届全国人大四次会议3月5日上午9时在人民大会堂开幕。国务院总理李克强作政府工作报告。 李...,3月5日上午，十三届全国人大四次会议，李克强总理作政府工作报告现场直播。 （原题为《直播见...,sl2_a,sl,408,78
3,最新！新增确诊病例10例！美国死亡人数已达50多万，白宫降半旗,图源：图虫创意 芥末堆讯2月22日，黑龙江绥化市疫情防控应急指挥部发布公告称，望奎县已连续...,sl3_a,sl,31,554
4,韩德君21分8篮板2助攻,北京时间1月31日，辽宁队在下午15：30开球的比赛中，以117-95轻松战胜上海队。辽宁...,sl4_a,sl,12,660
...,...,...,...,...,...,...
9933,骑士方面已经决定和德拉蒙德分道扬镳，这样做是为了保证他不受伤，避免影响到交易的完成。跟进的报...,勇士击败骑士取得31分的大胜，追梦三节送出16次助攻，7场助攻86次成为自1970年有相关统...,sl4964_b,sl,131,942
9934,解读1站后折返：乘客需下车，空车进行“掉头”解密地铁站：3号线宏图大道站多数地铁采用“站后折...,地铁2号线周边学校众多，“客服中心”放置“助学防疫包”，学生乘客可随时取用今天是中小学开学第...,sl4965_b,sl,106,753
9935,市直行业主管部门对各区（市、县、开发区）审核上报的名单在3个工作日内复核完毕，并会同市财政局...,新华社广州2月9日电（记者车晓蕙詹奕嘉黄浩苑）中国传统节日春节将至，位于东莞市沙田镇的美资企...,sl4966_b,sl,136,1363
9936,近日，陈亚男在社交平台中分享了她创立公司的好消息，从图中我们得知，陈亚男在经历了100天的努...,近日，有网友晒出一段大衣哥儿媳妇的视频，并配文“努力了100多天，终于有自己的公司了”，疑似...,sl4967_b,sl,96,1099
9937,女神节快乐喜讯！喜讯！一年一度的三八女神节来临之际，洛阳市妇幼保健院生殖医学研究所为答谢广大...,2021年3月4日下午，十堰市疾控中心举办迎“三八”女性健康知识讲座暨普法视频集中观看活动，...,sl4968_b,sl,133,532

In [28]:
data = []

with open('长长匹配A类/test_with_id.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
with open('长长匹配B类/test_with_id.txt', encoding='utf-8')as f:
    for line in f.readlines():
        data.append(json.loads(line))
        
df3 = pd.DataFrame(data)
df3['type'] = 'll'
df3['len1'] = df3['source'].apply(len)
df3['len2'] = df3['target'].apply(len)

print(df3.len1.describe(), df3.len2.describe())
df3

count    10020.000000
mean      1048.446407
std        996.569648
min        113.000000
25%        545.750000
50%        829.000000
75%       1222.000000
max      29006.000000
Name: len1, dtype: float64 count    10020.000000
mean      1070.158882
std       1041.282507
min        117.000000
25%        551.000000
50%        837.000000
75%       1250.250000
max      26831.000000
Name: len2, dtype: float64

,source,target,id,type,len1,len2
0,这世上多少父母自身的愿望在未能实现的时候，都寄托在了儿女身上。但纵然是能够寄托在儿女身上，...,这绝对是虾有生之年看过的最狗血的电视剧，没有之一。 ——2021年1月13日星期三盐大虾记 ...,ll0_a,ll,2947,2795
1,西班牙国王杯赛制：共分为六轮 首轮：是丙级球队和有资格参赛的丁级球队先进行一轮淘汰赛，决出...,北京时间1月17日19点，20/21赛季国王杯1/16决赛打响，西班牙人对阵奥萨苏纳。上半场...,ll1_a,ll,997,614
2,今天的NBA赛场静悄悄，因为各支球队都没有比赛要打，他们可以开始休整，而明星球员则要准备参加...,NBA全明星周末，布克因伤缺席，顶替他加入杜兰特队的是康利，同时康利还会顶替布克，参加三分大...,ll2_a,ll,512,706
3,▽ <今日银行招聘> ▽ 山东地区 2021年广发银行济南分行莱芜支行（筹）招聘公告 招聘...,交通银行信用卡中心公告来袭！ 校园&社会招聘公告齐发~ 专业宽松，无英语要求 部分岗位入职年...,ll3_a,ll,644,707
4,赵立坚资料图 2月25日，外交部发言人赵立坚主持例行记者会。 问：我们看到，近日中国对蒙古...,2月20日下午，首批由中国科兴公司生产的新冠疫苗运抵哥伦比亚首都波哥大。此前一天，中国政府援...,ll4_a,ll,396,2422
...,...,...,...,...,...,...
10015,郑秀文1972年出生在香港，是上世纪90年代人们的回忆，当时在香港是具有代表性的一位女歌手，...,就一眼爱变成了一种天赋 不自觉能和你笑抱你哭 我为你有了旅途 不管离天涯几步 我都不在乎 这...,ll5005_b,ll,985,2412
10016,本季MVP候选人之一的火箭「胡子」JamesHarden（哈登），今天在与国王赛后受访时表示...,威少不在乎MVP新浪体育讯北京时间12月12日，据美媒体报道，本赛季开始以来，雷霆队当家球星...,ll5006_b,ll,554,415
10017,在全球范围内，对新冠病毒的限制正在收紧，这给航运业，尤其是对海员换班带来了新的压力。 随着...,预警！马上杀到阜阳！做好防护！（点击查看）刚刚！成功！市二院医生跪了那么久…（点击查看） 我...,ll5007_b,ll,1414,4928
10018,苏提达不如诗妮娜那么能屈能伸，在昨天的活动上，苏提达等到了机会可以和泰王一起出席活动，她却控...,在诗妮娜贵妃风光复宠之后，苏提达王后确实变得比之前低调了很多，大家也很少看到她公开现身的画...,ll5008_b,ll,1087,410
10019,3月4日，知名艺术家孔宁在社交平台中晒出一组跟倪萍的合照，两人一起画画合影看起来非常亲密，文...,热播中的《青春有你3》受到了极高的度，许多网民都会定时观赏这一部综艺。而就在今日（5日），孙...,ll5009_b,ll,490,577

In [29]:
df = pd.concat([df1,df2,df3])
df

,source,target,id,type,len1,len2
0,北京顺义2个地区调整为低风险地区,黑龙江省大庆市中风险地区清零全域调为低风险,ss0_a,ss,16,21
1,库里夺冠希望渺茫！荣誉或就此而止，退役后进不了历史前十,维金斯：勇士文化是不同的这可能是我生涯最开心的阶段,ss1_a,ss,27,25
2,过年了，过年了！,就地过年的你，许愿吗？,ss2_a,ss,8,14
3,你见过被噎死的蛇吗？这条蛇自作自受吞下庞然大物把自己给撑死了！,这种瓜有人从来没见过，这里却做全瓜宴,ss3_a,ss,31,20
4,如果你喜欢关注足球赛事、喜欢讨论赛事战术打法、了解豪门球队背后的历史渊源、喜爱投资足彩竞彩…...,大家好，我是小狼！前天利物浦客场3:1击败铁锤帮西汉姆联，红军打进的第二个进球太漂亮了，就像...,ss4_a,ss,148,150
...,...,...,...,...,...,...
10015,郑秀文1972年出生在香港，是上世纪90年代人们的回忆，当时在香港是具有代表性的一位女歌手，...,就一眼爱变成了一种天赋 不自觉能和你笑抱你哭 我为你有了旅途 不管离天涯几步 我都不在乎 这...,ll5005_b,ll,985,2412
10016,本季MVP候选人之一的火箭「胡子」JamesHarden（哈登），今天在与国王赛后受访时表示...,威少不在乎MVP新浪体育讯北京时间12月12日，据美媒体报道，本赛季开始以来，雷霆队当家球星...,ll5006_b,ll,554,415
10017,在全球范围内，对新冠病毒的限制正在收紧，这给航运业，尤其是对海员换班带来了新的压力。 随着...,预警！马上杀到阜阳！做好防护！（点击查看）刚刚！成功！市二院医生跪了那么久…（点击查看） 我...,ll5007_b,ll,1414,4928
10018,苏提达不如诗妮娜那么能屈能伸，在昨天的活动上，苏提达等到了机会可以和泰王一起出席活动，她却控...,在诗妮娜贵妃风光复宠之后，苏提达王后确实变得比之前低调了很多，大家也很少看到她公开现身的画...,ll5008_b,ll,1087,410
10019,3月4日，知名艺术家孔宁在社交平台中晒出一组跟倪萍的合照，两人一起画画合影看起来非常亲密，文...,热播中的《青春有你3》受到了极高的度，许多网民都会定时观赏这一部综艺。而就在今日（5日），孙...,ll5009_b,ll,490,577

In [30]:
df.to_csv('test.csv', index=False)